In [258]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier


In [259]:
data=pd.read_csv('Boston.csv')

In [260]:
x = pd.DataFrame(dataset.iloc[:,:-1])
y = pd.DataFrame(dataset .iloc[:,-1])

In [261]:
x

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0             1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1             2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2             3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3             4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4             5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1   
502         503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1   
503         504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1   
504         505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1   
505         506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1   

     tax  ptratio   black  lstat  
0    296     15.3  396.90   4.98  
1    242     17.8  396.90   9.14  
2    242     17.8  392.83   4.03  
3    222     18.7  394.63   2.94  
4    222     18.7  396.90   5.33  
..   ...      ...     ...    ...  
501  273     21.0  391.99   9.67  
502  273     21.0  396.90   9.08  
503  273     21.0  396.90   5.64  
504  273     21.0  393.45   6.48  
505  273     21.0  396.90   7.88  

[506 rows x 14 columns]

In [262]:
y

medv
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [263]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# split training and testing data
xtrain,xtest,ytrain,ytest= train_test_split(
                                            x,y,
                                            test_size=0.2,
                                            random_state=1
                                           )
# creating object
stand= StandardScaler()
# fit data
Fit= stand.fit(xtrain)
# transform data
x_scaled = Fit.transform(xtrain)

In [264]:
regressor = LinearRegression()
regressor.fit(xtrain, ytrain)

LinearRegression()

In [265]:
v = pd.DataFrame(regressor.coef_,index=['Co-efficient']).transpose()
w = pd.DataFrame (x.columns, columns=['Attribute'])

In [266]:
coeff_df=pd.concat([w,v],axis=1,join='inner')
coeff_df


Attribute  Co-efficient
0   Unnamed: 0     -0.002717
1         crim     -0.113467
2           zn      0.060670
3        indus      0.019462
4         chas      2.155218
5          nox    -19.441797
6           rm      3.106845
7          age      0.002296
8          dis     -1.523417
9          rad      0.333528
10         tax     -0.010737
11     ptratio     -0.988933
12       black      0.007304
13       lstat     -0.547095

In [305]:
ytrain

medv
42   25.3
58   23.3
385   7.2
78   21.2
424  11.7
..    ...
255  20.9
72   22.8
396  12.5
235  24.0
37   21.0

[404 rows x 1 columns]

In [267]:
ft=regressor.predict(xtrain)
ft


array([[25.44228423],
       [22.38858062],
       [ 8.4204682 ],
       [21.61766821],
       [15.93573009],
       [32.61857586],
       [24.55072385],
       [25.48209352],
       [38.63805182],
       [29.05784392],
       [14.69730149],
       [34.90194595],
       [35.83938471],
       [33.16729259],
       [20.64863943],
       [17.05898681],
       [35.07190191],
       [39.54140638],
       [21.17370056],
       [15.44667312],
       [27.85089852],
       [19.03742084],
       [27.14103141],
       [20.52416727],
       [25.54081107],
       [21.25752547],
       [23.43872793],
       [28.65179436],
       [20.77881594],
       [23.66318772],
       [29.69010993],
       [10.52674321],
       [27.33269411],
       [32.58626734],
       [14.13493481],
       [13.37528258],
       [33.54586956],
       [13.50410845],
       [17.19927868],
       [16.38736849],
       [17.54422261],
       [28.60594158],
       [33.80924732],
       [20.15200692],
       [24.26438631],
       [17

In [268]:
y_pred = regressor.predict (xtest)
y_pred = pd.DataFrame(y_pred, columns=['Predicted'])
y_pred

Predicted
0    32.417338
1    27.790194
2    18.177707
3    21.813096
4    19.003303
..         ...
97   29.389236
98   37.104539
99   20.786951
100  17.416306
101  17.646926

[102 rows x 1 columns]

In [269]:
ytest.sort_index()

medv
4    36.2
5    28.7
6    22.9
11   18.9
17   17.5
..    ...
491  13.6
494  24.5
497  18.3
501  22.4
503  23.9

[102 rows x 1 columns]

In [270]:
from sklearn.metrics import r2_score

In [271]:
from sklearn import metrics

print('Mean Absolute Error: ',metrics.mean_absolute_error(ytest,y_pred))
print('Mean Square Error: ',metrics.mean_squared_error(ytest,y_pred))
print('Root Mean Square Error: ',np.sqrt(metrics.mean_squared_error(ytest,y_pred)))
print('',r2_score(ytest,y_pred))

Mean Absolute Error:  3.7357095670940104
Mean Square Error:  23.369625899561175
Root Mean Square Error:  4.834214093269058
 0.7635308791830625


In [272]:
#############3

In [273]:
data_=data.loc[:,['age','lstat','medv']]
data_.head(10)

age  lstat  medv
0   65.2   4.98  24.0
1   78.9   9.14  21.6
2   61.1   4.03  34.7
3   45.8   2.94  33.4
4   54.2   5.33  36.2
5   58.7   5.21  28.7
6   66.6  12.43  22.9
7   96.1  19.15  27.1
8  100.0  29.93  16.5
9   85.9  17.10  18.9

In [274]:
X = pd.DataFrame (data[['age','lstat']])
y = pd.DataFrame (data['medv'])


In [275]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split (X, y, test_size=0.2, random_state=1)


In [276]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [277]:
print (regressor.intercept_)

[33.26495503]


In [278]:
print (regressor.coef_)

[[ 0.02984524 -0.99935   ]]


In [298]:
sh=X_train.shape
sh

(404, 2)

In [279]:
import numpy as np
from sklearn import metrics
y_pred = regressor.predict(X_test)

In [280]:
y_pred

array([[27.83797009],
       [27.77289372],
       [17.02894325],
       [25.8089082 ],
       [25.95269088],
       [25.07403229],
       [29.2663887 ],
       [23.21795529],
       [18.15608677],
       [26.43345207],
       [27.76539471],
       [29.49660285],
       [21.60971133],
       [23.95979805],
       [24.25058296],
       [24.1273638 ],
       [12.82462213],
       [31.11511969],
       [26.98584184],
       [ 6.61033919],
       [24.09140538],
       [19.61030178],
       [26.59647672],
       [28.34572726],
       [29.12923584],
       [11.73804463],
       [15.83018001],
       [24.18929378],
       [28.67783874],
       [15.380202  ],
       [28.84996774],
       [16.91209003],
       [31.33889028],
       [19.71869145],
       [25.14188033],
       [20.95519584],
       [18.3635999 ],
       [29.55603169],
       [12.92465025],
       [20.67634237],
       [26.44306419],
       [27.66838437],
       [28.08139064],
       [12.08754662],
       [18.13270947],
       [12

In [281]:
y_test

medv
307  28.2
343  23.9
47   16.6
67   22.0
362  20.8
..    ...
92   22.9
224  44.8
110  21.7
426  10.2
443  15.4

[102 rows x 1 columns]

In [282]:
import numpy as np
from sklearn.metrics import r2_score
print('Mean Absolute Error: ',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Square Error: ',metrics.mean_squared_error(y_test,y_pred))
print('Root Mean Square Error: ',np.sqrt(metrics.mean_squared_error(y_test,y_pred)))
print('',r2_score(y_test,y_pred))



Mean Absolute Error:  5.115471184760084
Mean Square Error:  45.768411039762675
Root Mean Square Error:  6.76523547555905
 0.5368853585301029


In [283]:
xx=np.array([[37.5,4.65]])
yso=regressor.predict(xx)

C:\Users\THANH DUOC\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [284]:
yso

array([[29.73717413]])

In [288]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# split training and testing data
xtrain,xtest,ytrain,ytest= train_test_split(
                                            X,y,
                                            test_size=0.2,
                                            random_state=1
                                           )
# creating object
stand= StandardScaler()
# fit data
Fit= stand.fit(xtrain)
# transform data
x_scaled = Fit.transform(xtrain)

In [289]:
x_scaled

array([[-2.15002959e+00, -9.66850164e-01],
       [-1.35782026e+00, -8.21167893e-01],
       [ 1.05736657e+00,  2.50177533e+00],
       [-4.99009272e-01, -6.08451860e-02],
       [ 9.33950447e-02,  6.07905809e-01],
       [ 8.64572262e-01, -1.00986112e+00],
       [ 3.02987269e-02,  5.15382799e-02],
       [ 1.17932502e-01, -7.08784428e-01],
       [-5.37568133e-01, -1.33452447e+00],
       [ 5.66617428e-01, -5.18703751e-01],
       [ 3.56296369e-01,  1.21283409e+00],
       [ 1.38964608e-01, -8.75278451e-01],
       [ 1.12396824e+00, -6.92135025e-01],
       [-1.45947544e+00, -1.37476052e+00],
       [-7.89953404e-01, -4.21582237e-01],
       [-1.09842429e+00, -1.51029449e-01],
       [-1.82753730e+00, -1.49824359e+00],
       [-3.27975909e-02, -7.40695782e-01],
       [-1.47700220e+00, -3.89670882e-01],
       [ 9.17152527e-01,  8.22960589e-01],
       [-2.27972757e+00, -1.10143283e+00],
       [ 8.11991997e-01,  1.95833100e-01],
       [-1.57865738e+00, -4.53493591e-01],
       [-9.

In [301]:
from sklearn.metrics import mean_absolute_percentage_error
mape = mean_absolute_percentage_error(y_test, y_pred)
mape

0.2382909630228522

In [303]:
intercept = regressor.intercept_
intercept

array([33.26495503])

In [307]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

# Đường dẫn tới file "boston.csv"
file_path = "boston.csv"

# Đọc file CSV bằng pandas
data = pd.read_csv(file_path)

# Chuẩn bị dữ liệu đầu vào và đầu ra
X = data[['age', 'lstat']]
y = data['medv']

# Khởi tạo StandardScaler
scaler = StandardScaler()

# Chuẩn hóa dữ liệu đầu vào
X_scaled = scaler.fit_transform(X)

# Chia tập dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.1, random_state=10)

# Xây dựng mô hình hồi quy tuyến tính
model = LinearRegression()

# Huấn luyện mô hình trên tập huấn luyện
model.fit(X_train, y_train)

# Dự báo giá trị medv
X_input = [[37.5, 4.65]]
X_input_scaled = scaler.transform(X_input)
prediction = model.predict(X_input_scaled)

# In giá trị dự báo medv
print("Giá trị dự báo medv:", prediction[0])

Giá trị dự báo medv: 29.454798629362067


C:\Users\THANH DUOC\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
