In [25]:
import pandas as pd
df = pd.read_csv('./boston.csv')

FileNotFoundError: [Errno 2] No such file or directory: './boston.csv'

In [ ]:
# Tập dử liệu Input (đặc trưng) và Output (mục tiêu)
x = df[['AGE', 'LSTAT']].values # input
y = df[['MEDV']].values  # output

In [ ]:
# chia tách ra training (huấn luyện) và testing (kiểm thử)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=16)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
import math 
def silu(x):
    return x / (1 + np.exp(-x))

x_train = silu(x_train)
x_test = silu(x_test)
# Tạo và huấn luyện MinMaxScaler
scaler = PolynomialFeatures(degree=2)
x_train_scaled = scaler.fit_transform(x_train)
# Tạo và huấn luyện mô hình Linear Regression trên dữ liệu đã được chuẩn hóa
regressor = LinearRegression()
regressor.fit(x_train_scaled, y_train)


LinearRegression()

In [ ]:
print(x_train.shape)


(379, 2)


In [ ]:
# Dòng đầu tiên sau khi tiến hành chuẩn hóa dử liệu trên tập dử liệu đầu vào cho tập train
x_train_scaled

array([[1.00000000e+00, 1.00000000e+02, 2.03200000e+01, 1.00000000e+04,
        2.03200000e+03, 4.12902399e+02],
       [1.00000000e+00, 1.00000000e+02, 2.00800000e+01, 1.00000000e+04,
        2.00800000e+03, 4.03206398e+02],
       [1.00000000e+00, 4.03000000e+01, 1.04196892e+01, 1.62409000e+03,
        4.19913474e+02, 1.08569923e+02],
       ...,
       [1.00000000e+00, 8.41000000e+01, 1.42699909e+01, 7.07281000e+03,
        1.20010624e+03, 2.03632641e+02],
       [1.00000000e+00, 1.84999998e+01, 6.34902022e+00, 3.42249994e+02,
        1.17456873e+02, 4.03100577e+01],
       [1.00000000e+00, 9.52000000e+01, 1.13198627e+01, 9.06304000e+03,
        1.07765093e+03, 1.28139292e+02]])

In [ ]:
# Hệ số tự do
print(regressor.intercept_)

[37.72824962]


In [ ]:
# Dòng đầu tiên trên dử liệu đầu ra trên tập dữ liệu train
y_train[0]

array([7.2])

In [ ]:
# Hệ số gốc
print(regressor.coef_)

[[ 0.00000000e+00  8.86410682e-02 -2.19456503e+00  7.47947773e-04
  -1.09823172e-02  6.23890608e-02]]


In [ ]:
import numpy as np
from sklearn import metrics
 
scaler.fit(x_test)

# Biến đổi dữ liệu kiểm thử
x_test_scaled = scaler.transform(x_test)

y_test_pred = regressor.predict(x_test_scaled)

print('Score or R-Squared: ', regressor.score(x_test_scaled, y_test))

# print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_test_pred))
# print('Mean Squared Error:     ', metrics.mean_squared_error(y_test, y_test_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
print('Mean Absolute Percentage Error: ', metrics.mean_absolute_percentage_error(y_test, y_test_pred))

NameError: name 'scaler' is not defined

In [ ]:
# Kết quả dự báo đầu tiên cho giá trị medv
y_test_pred[0]

array([33.15607485])

In [ ]:
# Dự báo giá trị medv khi biết giá trị vAge = 37.5 và vIstat = 4.65
vAge = 37.5 
vIstat = 4.65

scaled = scaler.transform([[vAge, vIstat]])

print(f"Giá trị vAge và vIstat sau khi scale: {scaled}")

predicted = regressor.predict(scaled)

print(f"Giá trị dự báo medv: {predicted[0]}")

Giá trị vAge và vIstat sau khi scale: [[1.00000e+00 3.75000e+01 4.65000e+00 1.40625e+03 1.74375e+02 2.16225e+01]]
Giá trị dự báo medv: [31.33332977]
