In [2]:
# Data->MinMaxScaler -> modal
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import linear_model
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn import metrics 



In [3]:
df= pd.read_csv('dulieuxettuyendaihoc.csv', header=0,delimiter=',', encoding ='utf-8')
df

MSSV   T1   T2   T3   T4   T5   T6 GT  DT   KV  NGONNGU  \
0     SV001  7.2  8.4  7.4  7.2  7.4  6.9  F NaN  2NT     3.25   
1     SV002  5.4  6.3  4.3  4.9  3.0  4.0  M NaN    1     6.00   
2     SV003  5.6  5.0  2.8  6.1  4.8  5.7  M NaN    1     5.00   
3     SV004  6.6  5.1  5.9  4.1  6.1  7.4  M NaN    1     4.25   
4     SV005  6.0  5.4  7.6  4.4  6.8  8.0  M NaN  2NT     4.25   
..      ...  ...  ...  ...  ...  ...  ... ..  ..  ...      ...   
95   SV0096  8.6  8.9  7.7  6.7  7.9  6.6  F NaN    1     5.25   
96   SV0097  3.7  4.1  3.1  3.4  5.5  5.7  F NaN    1     5.25   
97   SV0098  8.8  9.5  9.5  8.5  9.0  8.5  M NaN  2NT     7.00   
98   SV0099  2.7  2.8  6.2  5.2  4.1  4.3  M NaN    1     5.00   
99  SV00100  4.1  4.4  6.0  4.3  5.6  5.1  M NaN  2NT     5.25   

    TOANLOGICPHANTICH  GIAIQUYETVANDE  KT    NGAYTHI DINHHUONGNGHENGHIEP  
0                3.25            4.50  A1  12/7/2018                  No  
1                4.00            3.50   C  12/7/2018                 Yes  
2                6.75            4.00   C  12/7/2018                  No  
3                4.25            5.25  D1  12/7/2018                  No  
4                4.50            5.00   A  12/7/2018                  No  
..                ...             ...  ..        ...                 ...  
95               1.50            6.25   C  7/20/2022                 Yes  
96               3.75            4.75   C  7/20/2022                  No  
97               8.00            4.00   C  7/20/2022                 Yes  
98               3.50            5.50   C  7/20/2022                  No  
99               2.50            4.25   C  7/20/2022                 Yes  

[100 rows x 16 columns]

In [4]:
df.rename(columns={'TOANLOGICPHANTICH':'LOGIC','GIAIQUYETVANDE':'UNGXU','DINHHUONGNGHENGHIEP':'HUONGNGHIEP'},inplace=True)

In [5]:
df = df[['T1','T2','T3','T4','T5','T6','GT','LOGIC']]
df

T1   T2   T3   T4   T5   T6 GT  LOGIC
0   7.2  8.4  7.4  7.2  7.4  6.9  F   3.25
1   5.4  6.3  4.3  4.9  3.0  4.0  M   4.00
2   5.6  5.0  2.8  6.1  4.8  5.7  M   6.75
3   6.6  5.1  5.9  4.1  6.1  7.4  M   4.25
4   6.0  5.4  7.6  4.4  6.8  8.0  M   4.50
..  ...  ...  ...  ...  ...  ... ..    ...
95  8.6  8.9  7.7  6.7  7.9  6.6  F   1.50
96  3.7  4.1  3.1  3.4  5.5  5.7  F   3.75
97  8.8  9.5  9.5  8.5  9.0  8.5  M   8.00
98  2.7  2.8  6.2  5.2  4.1  4.3  M   3.50
99  4.1  4.4  6.0  4.3  5.6  5.1  M   2.50

[100 rows x 8 columns]

In [6]:
df.describe()

T1          T2          T3          T4          T5        T6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.0000   
mean     5.946000    6.374000    6.383000    6.291000    6.717000    6.9370   
std      1.608338    1.561443    1.574484    1.469563    1.478059    1.3632   
min      2.400000    2.800000    2.300000    2.900000    3.000000    3.7000   
25%      5.000000    5.300000    5.175000    5.300000    5.800000    6.0000   
50%      5.850000    6.250000    6.650000    6.350000    6.800000    7.1000   
75%      7.200000    7.525000    7.500000    7.600000    7.800000    8.0000   
max      9.300000    9.600000    9.500000    9.400000    9.500000    9.5000   

            LOGIC  
count  100.000000  
mean     4.255000  
std      1.060053  
min      1.500000  
25%      3.500000  
50%      4.125000  
75%      4.750000  
max      8.000000

In [7]:
GT=pd.get_dummies(df['GT']).astype(int)
GT
# True = 1
# Flase =0

F  M
0   1  0
1   0  1
2   0  1
3   0  1
4   0  1
.. .. ..
95  1  0
96  1  0
97  0  1
98  0  1
99  0  1

[100 rows x 2 columns]

In [8]:
df=pd.concat([df,GT],axis=1)
df.head(5)
df.drop('GT',axis=1,inplace=True)
df

T1   T2   T3   T4   T5   T6  LOGIC  F  M
0   7.2  8.4  7.4  7.2  7.4  6.9   3.25  1  0
1   5.4  6.3  4.3  4.9  3.0  4.0   4.00  0  1
2   5.6  5.0  2.8  6.1  4.8  5.7   6.75  0  1
3   6.6  5.1  5.9  4.1  6.1  7.4   4.25  0  1
4   6.0  5.4  7.6  4.4  6.8  8.0   4.50  0  1
..  ...  ...  ...  ...  ...  ...    ... .. ..
95  8.6  8.9  7.7  6.7  7.9  6.6   1.50  1  0
96  3.7  4.1  3.1  3.4  5.5  5.7   3.75  1  0
97  8.8  9.5  9.5  8.5  9.0  8.5   8.00  0  1
98  2.7  2.8  6.2  5.2  4.1  4.3   3.50  0  1
99  4.1  4.4  6.0  4.3  5.6  5.1   2.50  0  1

[100 rows x 9 columns]

In [9]:
x=df[['T1','T2','T3','T4','T5','T6','F','M']].values # input frature dac Trung
y=df['LOGIC'].values # output muc tieu (Target)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size= 0.2,random_state=16)


In [11]:
x_train

array([[3.7, 4.1, 3.1, 3.4, 5.5, 5.7, 1. , 0. ],
       [9.3, 9.6, 7.1, 8.5, 8.5, 7.8, 0. , 1. ],
       [8.1, 8.8, 9.2, 8.8, 8.9, 8.5, 0. , 1. ],
       [4.9, 6.1, 2.5, 6.2, 4.9, 6.5, 0. , 1. ],
       [4.6, 7.2, 7.6, 6.2, 8. , 7.2, 0. , 1. ],
       [5.7, 3.9, 5.7, 4.6, 6.8, 7.3, 0. , 1. ],
       [4.3, 5.3, 7.3, 7.7, 7.4, 7.1, 0. , 1. ],
       [7.9, 8.2, 8.1, 6.9, 8. , 8.1, 0. , 1. ],
       [5.2, 6.3, 7.8, 7.6, 6.2, 7.3, 1. , 0. ],
       [6.3, 6.3, 5.2, 6.1, 6. , 5.7, 0. , 1. ],
       [6.9, 5.4, 5.3, 5.3, 7.2, 7.1, 1. , 0. ],
       [6.5, 5.3, 6.1, 5.7, 7.1, 6.9, 0. , 1. ],
       [4.4, 4.4, 5.1, 5.6, 5.8, 5.8, 0. , 1. ],
       [5.6, 5. , 2.8, 6.1, 4.8, 5.7, 0. , 1. ],
       [5.8, 6.4, 7.3, 7.1, 7.3, 6.7, 0. , 1. ],
       [8.2, 6.4, 6.1, 5.8, 7.1, 8.9, 1. , 0. ],
       [7.3, 7.5, 8. , 7.7, 7.8, 8.1, 0. , 1. ],
       [7.3, 5.9, 7.1, 7.7, 7.9, 6.6, 0. , 1. ],
       [8.1, 4.4, 5. , 2.9, 5.8, 5.6, 1. , 0. ],
       [5. , 5.5, 2.3, 4.1, 3.4, 4.1, 1. , 0. ],
       [6. , 7.3, 7.

In [12]:
# x*x
x_train_BP = np.square(x_train)
x_train_BP[0]
# hàm X_train như nào thì X_Test cũng phải i chang


array([13.69, 16.81,  9.61, 11.56, 30.25, 32.49,  1.  ,  0.  ])

In [13]:
# Sqrt
x_train_SQRT = np.sqrt(x_train_BP)
x_train_SQRT[0]

array([3.7, 4.1, 3.1, 3.4, 5.5, 5.7, 1. , 0. ])

In [14]:
# # log
# x_train_log = np.log(x_train_SQRT)
# x_train_log

In [15]:
# minmaxScaler 
scaler = MinMaxScaler()
x_train_scaled = scaler.fit_transform(x_train_SQRT)
x_train_scaled[0]

array([0.1884058 , 0.12698413, 0.11111111, 0.08474576, 0.38461538,
       0.34482759, 1.        , 0.        ])

In [16]:
# poly 
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train_scaled)

In [17]:
# nào khúc cuối mới tạo regressor và gắn nó cho phần X_train 
regressor = LinearRegression()
regressor.fit(x_train_poly, y_train)

LinearRegression()

In [18]:
# Hệ số tự do
print(regressor.intercept_)
# Hệ số gốc
print(regressor.coef_)

-2257735061670.7515
[ 2.25773506e+12  3.81059709e-01 -2.40965926e+00 -2.11168511e+00
  2.34309141e+00 -7.36455740e+00  6.93616761e+00  1.88193818e-01
 -1.88193818e-01  6.08927315e+00 -2.46380751e+00 -1.23387802e+01
 -4.90459958e+00  1.26038788e+01 -5.70934254e+00 -6.48567193e-01
  1.02962690e+00 -3.31738200e+00  1.54560148e+01  6.51900464e-01
 -6.47825951e+00  4.23666180e+00 -3.18168784e+00  7.72028571e-01
  7.76385360e+00 -1.16289854e+01 -4.57076163e+00  2.37291864e+00
 -1.01896926e+00 -1.09271585e+00 -6.84559353e+00  2.22741547e+01
 -1.16546633e+00  3.48243440e+00 -1.13934299e+00  2.02334155e-01
 -3.26281687e+00 -4.74939442e+00 -2.61516298e+00 -5.61436507e+00
  3.82931291e+00  3.10685470e+00  1.88193818e-01  0.00000000e+00
 -1.88193818e-01]


# X_Test gắn hàm số dô


In [19]:
# x*x
x_test_BP = np.square(x_test)
# Sqrt
x_test_SQRT = np.sqrt(x_test_BP)
# # minmaxScaler 
scaler = MinMaxScaler()
x_test_scaled = scaler.fit_transform(x_test_SQRT)
# # poly 
# poly = PolynomialFeatures(degree=2)
# x_test_poly = poly.fit_transform(x_test_scaled)

In [20]:
import numpy as np
from sklearn import metrics

scaler.fit(x_test_scaled)

#đánh giá mô hình
# Biến đổi dữ liệu kiểm thử
x_test_scaled = poly.transform(x_test_scaled)
y_test_pred = regressor.predict(x_test_scaled)

print('Score or R-Squared: ', regressor.score(x_test_scaled, y_test))

# print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_test_pred))
# print('Mean Squared Error:     ', metrics.mean_squared_error(y_test, y_test_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
print('Mean Absolute Percentage Error: ', metrics.mean_absolute_percentage_error(y_test, y_test_pred))

Score or R-Squared:  -2.8279919500214827
Root Mean Squared Error:  1.8872802878074448
Mean Absolute Percentage Error:  0.4093742505025014


In [21]:
x_test_scaled

array([[1.00000000e+00, 9.82456140e-01, 6.00000000e-01, 1.00000000e+00,
        7.70833333e-01, 9.78260870e-01, 8.07017544e-01, 1.00000000e+00,
        0.00000000e+00, 9.65220068e-01, 5.89473684e-01, 9.82456140e-01,
        7.57309942e-01, 9.61098398e-01, 7.92859341e-01, 9.82456140e-01,
        0.00000000e+00, 3.60000000e-01, 6.00000000e-01, 4.62500000e-01,
        5.86956522e-01, 4.84210526e-01, 6.00000000e-01, 0.00000000e+00,
        1.00000000e+00, 7.70833333e-01, 9.78260870e-01, 8.07017544e-01,
        1.00000000e+00, 0.00000000e+00, 5.94184028e-01, 7.54076087e-01,
        6.22076023e-01, 7.70833333e-01, 0.00000000e+00, 9.56994329e-01,
        7.89473684e-01, 9.78260870e-01, 0.00000000e+00, 6.51277316e-01,
        8.07017544e-01, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [1.00000000e+00, 1.57894737e-01, 2.15384615e-01, 0.00000000e+00,
        4.16666667e-02, 3.91304348e-01, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 2.49307479e-02,

In [22]:
import numpy as np
from sklearn import metrics

scaler.fit(x_train_scaled)

#đánh giá mô hình
# Biến đổi dữ liệu kiểm thử
x_train_scaled = poly.transform(x_train_scaled)
y_train_pred = regressor.predict(x_train_scaled)

print('Score or R-Squared: ', regressor.score(x_train_scaled, y_train))

# print('Mean Absolute Error: ', metrics.mean_absolute_error(y_train, y_train_pred))
# print('Mean Squared Error:     ', metrics.mean_squared_error(y_train, y_train_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_train, y_train_pred)))
print('Mean Absolute Percentage Error: ', metrics.mean_absolute_percentage_error(y_train, y_train_pred))

Score or R-Squared:  0.42272482477178974
Root Mean Squared Error:  0.8135024470759645
Mean Absolute Percentage Error:  0.1567251034967009


In [23]:
vT1 = 5.0 
vT2 = 6.5 
vT3 = 7.0 
vT4 = 7.0 
vT5 = 6.5
vT6 = 6.0 
vM = 1
vF = 0
scaled = poly.transform([[vT1,vT2,vT3,vT4,vT5,vT6,vM,vF]])

print(f"Giá trị T1 đến T6 sau khi sacle: {scaled}")

predicted_logic = regressor.predict(scaled)

print(f"Giá trị dự báo điểm logic: {predicted_logic}")

Giá trị T1 đến T6 sau khi sacle: [[ 1.    5.    6.5   7.    7.    6.5   6.    1.    0.   25.   32.5  35.
  35.   32.5  30.    5.    0.   42.25 45.5  45.5  42.25 39.    6.5   0.
  49.   49.   45.5  42.    7.    0.   49.   45.5  42.    7.    0.   42.25
  39.    6.5   0.   36.    6.    0.    1.    0.    0.  ]]
Giá trị dự báo điểm logic: [174.31933594]
