In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [30]:

social_N_data = pd.read_csv('Social_Network_Ads.csv')

In [31]:
social_N_data

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [32]:
gender = pd.get_dummies(social_N_data['Gender'], drop_first=True)
gender

Male
0     True
1     True
2    False
3    False
4     True
..     ...
395  False
396   True
397  False
398   True
399  False

[400 rows x 1 columns]

In [33]:
social_N_data.drop('Gender',axis=1,inplace=True)

In [34]:
social_N_data = pd.concat([social_N_data,gender], axis=1)

In [35]:
social_N_data.head()

User ID  Age  EstimatedSalary  Purchased   Male
0  15624510   19            19000          0   True
1  15810944   35            20000          0   True
2  15668575   26            43000          0  False
3  15603246   27            57000          0  False
4  15804002   19            76000          0   True

In [36]:
X = social_N_data.iloc[:,[1,2,4]] # Age, EstimatedSalary and Male
X.head()

Age  EstimatedSalary   Male
0   19            19000   True
1   35            20000   True
2   26            43000  False
3   27            57000  False
4   19            76000   True

In [37]:
y = social_N_data.iloc[:, 3] # Purchased
y.head()


0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X

array([[-1.78179743, -1.49004624,  1.02020406],
       [-0.25358736, -1.46068138,  1.02020406],
       [-1.11320552, -0.78528968, -0.98019606],
       ...,
       [ 1.17910958, -1.46068138, -0.98019606],
       [-0.15807423, -1.07893824,  1.02020406],
       [ 1.08359645, -0.99084367, -0.98019606]])

In [39]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=10)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(360, 3)
(40, 3)
(360,)
(40,)


In [40]:
X_train

array([[ 0.31949142, -0.72655996,  1.02020406],
       [ 0.70154394, -0.72655996, -0.98019606],
       [-1.30423178, -1.49004624,  1.02020406],
       ...,
       [-0.82666613,  0.30121002,  1.02020406],
       [ 0.12846516, -0.25672226, -0.98019606],
       [ 0.41500455,  1.123426  , -0.98019606]])

In [41]:
from sklearn.linear_model import LogisticRegression  
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
# flatten() đổi ra dạng số 


LogisticRegression()

In [42]:
classifier.coef_

array([[2.15200421, 1.08592164, 0.15798615]])

In [59]:
y_pred = classifier.predict(X_test)
result = pd.DataFrame({'Actual' : y_test, 'Predicted' : y_pred})
result

Actual  Predicted
332       0          0
111       0          0
352       1          1
205       0          1
56        0          0
379       1          1
81        0          0
214       0          1
142       0          0
110       0          0
119       0          0
172       0          0
373       1          1
274       1          1
24        1          0
276       0          0
78        0          0
65        0          0
43        0          0
339       1          1
47        0          0
105       0          0
351       0          0
280       1          1
366       1          1
113       0          0
241       0          0
253       1          1
390       1          1
398       0          0
1         0          0
6         0          0
183       0          0
26        1          1
331       1          1
173       0          0
367       1          1
208       1          1
154       0          0
138       0          0

In [44]:
classifier.coef_
# array([[2.36839196, 1.42929561, 0.20973787]])
# 3 đặc trưng của mảng
classifier.intercept_
#hệ số góc của mô hì

array([-1.03526656])

In [45]:
# Câu 1 
tuoi = X_train[:-1][0]
print("Tuổi của dòng cuối cùng trong tập dữ liệu train:", tuoi)

Tuổi của dòng cuối cùng trong tập dữ liệu train: [ 0.31949142 -0.72655996  1.02020406]


In [46]:
classifier.intercept_   
# Đây là hệ số góc của mô hình logistic regression

array([-1.03526656])

In [47]:
from sklearn.metrics import confusion_matrix
cf_matrix = confusion_matrix(y_test, y_pred)
cf_matrix

array([[24,  2],
       [ 1, 13]], dtype=int64)

In [60]:
y_test


332    0
111    0
352    1
205    0
56     0
379    1
81     0
214    0
142    0
110    0
119    0
172    0
373    1
274    1
24     1
276    0
78     0
65     0
43     0
339    1
47     0
105    0
351    0
280    1
366    1
113    0
241    0
253    1
390    1
398    0
1      0
6      0
183    0
26     1
331    1
173    0
367    1
208    1
154    0
138    0
Name: Purchased, dtype: int64

In [48]:
# 0 TN|FP       00||01
# 1 FN|TP       10||11

In [49]:
#Câu 4
# def silu(x):
#     return x / (1 + np.exp(-x))

# X_test=silu(X_test)
# print('prediction with threshold 0.45:')
# y_pred_test_new_threshold = (classifier.predict_proba(X_test)[:,1]>=0.45).astype(int)
# y_pred_test_new_threshold

In [50]:
#Câu 5: độ chính xác  
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.925

In [51]:
X_test

array([[ 0.41500455, -0.13926283,  1.02020406],
       [-0.0625611 ,  0.03692631, -0.98019606],
       [ 0.41500455,  0.59485858, -0.98019606],
       [ 0.89257019, -0.66783025, -0.98019606],
       [-1.39974491, -0.63846539, -0.98019606],
       [ 1.94321462, -1.37258681, -0.98019606],
       [ 0.12846516, -0.81465453,  1.02020406],
       [ 0.89257019, -0.78528968,  1.02020406],
       [-0.25358736, -0.31545197,  1.02020406],
       [ 0.12846516,  0.03692631, -0.98019606],
       [ 0.31949142, -0.31545197,  1.02020406],
       [-1.11320552,  1.41707457, -0.98019606],
       [ 2.03872775,  1.76945285,  1.02020406],
       [ 1.84770149, -1.28449224, -0.98019606],
       [ 0.79705706, -1.37258681,  1.02020406],
       [ 0.03295203,  0.03692631,  1.02020406],
       [-0.92217926,  0.50676401, -0.98019606],
       [-1.30423178, -0.34481683,  1.02020406],
       [-0.73115301, -1.60750566,  1.02020406],
       [ 0.12846516,  1.53453399,  1.02020406],
       [-1.01769239, -0.46227625, -0.980

In [52]:
# # câu 6 
# def silu(x):
#     return x / (1 + np.exp(-x))

# y_test=silu(y_test)
# y_test.iloc[0]

In [53]:
classifier.predict(X_test)

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [54]:
# câu 7 
X_train

array([[ 0.31949142, -0.72655996,  1.02020406],
       [ 0.70154394, -0.72655996, -0.98019606],
       [-1.30423178, -1.49004624,  1.02020406],
       ...,
       [-0.82666613,  0.30121002,  1.02020406],
       [ 0.12846516, -0.25672226, -0.98019606],
       [ 0.41500455,  1.123426  , -0.98019606]])

In [55]:
# câu 9
vT1 = 46
vT2 =  49000
vT3 = 0 
y_pred = classifier.predict([[vT1,vT2,vT3]])
print('Dự báo định hướng :' +str(y_pred[0]))

Dự báo định hướng :1


In [56]:
pd.DataFrame(X_test).to_csv("input_test.csv")
pd.DataFrame(y_test).to_csv("output_test.csv")
