In [29]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df=pd.read_csv('boston.csv',header=0,delimiter=',',encoding='utf-8')


In [31]:

df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [32]:
#Tập dữ liệu đặc trưng
x = df[['AGE','LSTAT']].values #input
y = df[['MEDV']].values #output


In [33]:
x

array([[65.2 ,  4.98],
       [78.9 ,  9.14],
       [61.1 ,  4.03],
       ...,
       [91.  ,  5.64],
       [89.3 ,  6.48],
       [80.8 ,  7.88]])

In [34]:
#Chia tách ra trainning(tập huấn) và testting(kiểm thử)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=16)

In [35]:
X_train

array([[ 92.7 ,  18.06],
       [  6.6 ,   6.72],
       [ 21.4 ,   8.43],
       [ 65.2 ,   4.98],
       [ 40.5 ,   3.95],
       [ 52.9 ,  11.22],
       [ 33.3 ,  14.15],
       [ 54.3 ,  11.38],
       [ 77.  ,   7.01],
       [ 31.1 ,   6.27],
       [ 68.2 ,   9.68],
       [ 63.  ,   9.43],
       [ 98.2 ,  16.96],
       [ 56.8 ,   8.44],
       [ 48.  ,   9.62],
       [  6.8 ,   3.53],
       [ 34.1 ,   4.08],
       [ 70.6 ,  14.1 ],
       [ 42.4 ,   9.47],
       [ 27.7 ,   6.36],
       [ 85.9 ,  17.1 ],
       [ 93.5 ,  16.9 ],
       [ 76.  ,   4.21],
       [ 91.8 ,  11.64],
       [ 34.2 ,   3.11],
       [100.  ,  20.32],
       [100.  ,  20.08],
       [ 40.3 ,  10.42],
       [ 21.9 ,   4.81],
       [ 15.3 ,   4.56],
       [ 52.3 ,   7.2 ],
       [ 94.  ,  16.14],
       [ 86.3 ,   5.5 ],
       [ 49.9 ,   7.7 ],
       [ 53.8 ,  16.03],
       [ 34.5 ,   8.01],
       [ 59.7 ,  15.69],
       [ 66.1 ,   8.81],
       [ 94.7 ,  18.34],
       [ 91.  ,  13.27],


In [36]:
X_train.shape

(404, 2)

In [37]:
y_train

array([[15.2],
       [24.2],
       [23.4],
       [24. ],
       [31.6],
       [22.2],
       [20. ],
       [22. ],
       [25. ],
       [28.6],
       [18.9],
       [20.5],
       [18.1],
       [22.2],
       [23.9],
       [29.6],
       [33.3],
       [18.3],
       [25. ],
       [23.1],
       [18.9],
       [17.4],
       [38.7],
       [22.7],
       [44. ],
       [ 7.2],
       [16.3],
       [21.8],
       [35.4],
       [34.9],
       [23.8],
       [13.1],
       [23.6],
       [20.4],
       [22.4],
       [21.1],
       [10.2],
       [22.6],
       [14.3],
       [21.7],
       [19.4],
       [12.5],
       [29.4],
       [21.2],
       [21.7],
       [15.2],
       [15. ],
       [26.7],
       [28.2],
       [19.9],
       [41.3],
       [24.1],
       [15. ],
       [23.1],
       [ 5. ],
       [19.6],
       [13.3],
       [28.7],
       [29. ],
       [42.8],
       [21. ],
       [22.8],
       [20.6],
       [ 8.5],
       [25. ],
       [44.8],
       [19

In [38]:
from sklearn.preprocessing import MinMaxScaler
#Scale cho inpput
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)

In [39]:
X_train

array([[0.92481977, 0.49424939],
       [0.03810505, 0.15102906],
       [0.19052523, 0.2027845 ],
       [0.64160659, 0.09836562],
       [0.38722966, 0.06719128],
       [0.51493306, 0.2872276 ],
       [0.3130793 , 0.37590799],
       [0.52935118, 0.29207022],
       [0.76313079, 0.1598063 ],
       [0.29042225, 0.1374092 ],
       [0.67250257, 0.24061743],
       [0.61894954, 0.23305085],
       [0.98146241, 0.46095642],
       [0.55509784, 0.20308717],
       [0.46446962, 0.23880145],
       [0.04016478, 0.05447942],
       [0.32131823, 0.07112591],
       [0.69721936, 0.37439467],
       [0.40679712, 0.2342615 ],
       [0.2554068 , 0.14013317],
       [0.85478888, 0.4651937 ],
       [0.9330587 , 0.45914044],
       [0.75283213, 0.07506053],
       [0.91555098, 0.29993947],
       [0.32234809, 0.04176755],
       [1.        , 0.56265133],
       [1.        , 0.55538741],
       [0.38516993, 0.26301453],
       [0.19567456, 0.09322034],
       [0.1277034 , 0.08565375],
       [0.

In [40]:
#Xây dựng mô hình hooid quy tuyến tính đa biến
# ? = A0 + A1*? + A2*? + epsilon
# điểm ngôn ngữ = A0 + T5-scale + T6-scale + epsilon
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X_train,y_train)
#
#
print(model.intercept_)

print(model.coef_)
#Sinh viên tự ghi lại mô hình

[31.26170026]
[[  5.58919129 -38.23018134]]


In [41]:
#Đánh giá mô hình
import numpy as np
from sklearn import metrics
X_test = sc.transform(X_test)

y_test_pred = model.predict(X_test)

print('Score or R-Squared:', model.score (X_test, y_test))

print('Mean Absolute Error:',
        metrics.mean_absolute_error(y_test, y_test_pred)) 

print('Mean Squared Error:',
        metrics.mean_squared_error(y_test, y_test_pred)) 

print('Root Mean Squared Error:',
        np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))


Score or R-Squared: 0.4069676937197577
Mean Absolute Error: 4.5918745715026485
Mean Squared Error: 39.24693104001137
Root Mean Squared Error: 6.264737108611292


In [42]:
#Ví dụ : T5 = 6 
#       T6 = 7.5
vAGE = 37.5
vLSTAT = 4.65
scaled = sc.transform([[vAGE,vLSTAT]])
print(f'T5 T6 sau khi scale : {scaled}')

predicted_ngonngu = model.predict(scaled)
print(f'Gia tri du bao MEDV : {predicted_ngonngu}')

T5 T6 sau khi scale : [[0.35633368 0.08837772]]
Gia tri du bao MEDV : [[29.87462092]]
