In [1]:
import pandas as pd
df = pd.read_csv('./boston.csv')

In [2]:
# Tập dử liệu Input (đặc trưng) và Output (mục tiêu)
x = df[['AGE', 'LSTAT']].values # input
y = df[['MEDV']].values  # output

In [3]:
# chia tách ra training (huấn luyện) và testing (kiểm thử)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=16)

In [4]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
import math 
def silu(x):
    return x / (1 + np.exp(-x))

x_train = silu(x_train)
x_test = silu(x_test)
# Tạo và huấn luyện MinMaxScaler
scaler = PolynomialFeatures(degree=2)
x_train_scaled = scaler.fit_transform(x_train)
# Tạo và huấn luyện mô hình Linear Regression trên dữ liệu đã được chuẩn hóa
regressor = LinearRegression()
regressor.fit(x_train_scaled, y_train)


LinearRegression()

In [5]:
print(x_train.shape)


(379, 2)


In [6]:
# Dòng đầu tiên sau khi tiến hành chuẩn hóa dử liệu trên tập dử liệu đầu vào cho tập train
x_train_scaled

array([[1.00000000e+00, 1.00000000e+02, 2.03200000e+01, 1.00000000e+04,
        2.03200000e+03, 4.12902399e+02],
       [1.00000000e+00, 1.00000000e+02, 2.00800000e+01, 1.00000000e+04,
        2.00800000e+03, 4.03206398e+02],
       [1.00000000e+00, 4.03000000e+01, 1.04196892e+01, 1.62409000e+03,
        4.19913474e+02, 1.08569923e+02],
       ...,
       [1.00000000e+00, 8.41000000e+01, 1.42699909e+01, 7.07281000e+03,
        1.20010624e+03, 2.03632641e+02],
       [1.00000000e+00, 1.84999998e+01, 6.34902022e+00, 3.42249994e+02,
        1.17456873e+02, 4.03100577e+01],
       [1.00000000e+00, 9.52000000e+01, 1.13198627e+01, 9.06304000e+03,
        1.07765093e+03, 1.28139292e+02]])

In [7]:
# Hệ số tự do
print(regressor.intercept_)

[37.72824962]


In [8]:
# Dòng đầu tiên trên dử liệu đầu ra trên tập dữ liệu train
y_train[0]

array([7.2])

In [9]:
# Hệ số gốc
print(regressor.coef_)

[[ 0.00000000e+00  8.86410682e-02 -2.19456503e+00  7.47947773e-04
  -1.09823172e-02  6.23890608e-02]]


PolynomialFeatures()

In [10]:
import numpy as np
from sklearn import metrics
 
scaler.fit(x_test)

# Biến đổi dữ liệu kiểm thử
x_test_scaled = scaler.transform(x_test)

y_test_pred = regressor.predict(x_test_scaled)

print('Score or R-Squared: ', regressor.score(x_test_scaled, y_test))

# print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_test_pred))
# print('Mean Squared Error:     ', metrics.mean_squared_error(y_test, y_test_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
print('Mean Absolute Percentage Error: ', metrics.mean_absolute_percentage_error(y_test, y_test_pred))

Score or R-Squared:  0.6957632695289517
Root Mean Squared Error:  4.428017053433868
Mean Absolute Percentage Error:  0.18515312729577654


In [15]:
y_test_pred

array([[33.15607485],
       [11.50037292],
       [13.81143399],
       [28.86222605],
       [19.1876972 ],
       [21.42147832],
       [21.1911529 ],
       [14.13118157],
       [16.39585031],
       [36.73296024],
       [14.48869735],
       [11.20474833],
       [11.60532193],
       [26.45342113],
       [18.99195454],
       [24.6016053 ],
       [24.93039947],
       [34.33877603],
       [18.44389924],
       [13.92154146],
       [26.49770526],
       [18.09069836],
       [10.95550865],
       [14.59841406],
       [12.29175756],
       [20.14709729],
       [11.12441097],
       [18.13346978],
       [13.32362649],
       [10.84771758],
       [22.98234201],
       [24.76511924],
       [17.62252382],
       [10.6249031 ],
       [11.13767493],
       [27.38539462],
       [18.13819305],
       [13.34993476],
       [32.81025329],
       [17.18264676],
       [26.61382378],
       [31.52069479],
       [29.98742136],
       [14.15362193],
       [18.78952283],
       [26

In [14]:
x_test_scaled

array([[1.00000000e+00, 1.00000000e+02, 7.38544026e+00, 1.00000000e+04,
        7.38544026e+02, 5.45447278e+01],
       [1.00000000e+00, 9.39000000e+01, 2.28800000e+01, 8.81721000e+03,
        2.14843200e+03, 5.23494400e+02],
       [1.00000000e+00, 7.78000000e+01, 2.99700000e+01, 6.05284000e+03,
        2.33166600e+03, 8.98200900e+02],
       [1.00000000e+00, 5.18000000e+01, 6.57088061e+00, 2.68324000e+03,
        3.40371615e+02, 4.31764720e+01],
       [1.00000000e+00, 9.84000000e+01, 1.45899933e+01, 9.68256000e+03,
        1.43565534e+03, 2.12867904e+02],
       [1.00000000e+00, 6.81000000e+01, 1.16498984e+01, 4.63761000e+03,
        7.93358083e+02, 1.35720133e+02],
       [1.00000000e+00, 9.07000000e+01, 1.28699669e+01, 8.22649000e+03,
        1.16730600e+03, 1.65636047e+02],
       [1.00000000e+00, 9.19000000e+01, 1.86599999e+01, 8.44561000e+03,
        1.71485399e+03, 3.48195595e+02],
       [1.00000000e+00, 9.93000000e+01, 1.67399991e+01, 9.86049000e+03,
        1.66228191e+03, 

In [11]:
# Kết quả dự báo đầu tiên cho giá trị medv
y_test_pred[0]

array([33.15607485])

In [12]:
# Dự báo giá trị medv khi biết giá trị vAge = 37.5 và vIstat = 4.65
vAge = 37.5 
vIstat = 4.65

scaled = scaler.transform([[vAge, vIstat]])

print(f"Giá trị vAge và vIstat sau khi scale: {scaled}")

predicted = regressor.predict(scaled)

print(f"Giá trị dự báo medv: {predicted[0]}")

Giá trị vAge và vIstat sau khi scale: [[1.00000e+00 3.75000e+01 4.65000e+00 1.40625e+03 1.74375e+02 2.16225e+01]]
Giá trị dự báo medv: [31.33332977]
