In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../Data/Tuan4/boston.csv', header=0, encoding='utf-8',delimiter=',')

In [2]:
df = df[['MEDV','AGE','LSTAT']]

In [4]:
df.head(5)

MEDV   AGE  LSTAT
0  24.0  65.2   4.98
1  21.6  78.9   9.14
2  34.7  61.1   4.03
3  33.4  45.8   2.94
4  36.2  54.2   5.33

In [20]:
X = df[['AGE','LSTAT']].values #input: đặc trưng (feature)
Y = df[['MEDV']].values #output: mục tiêu (tanget)

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=16)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LinearRegression 
regressor = LinearRegression()
regressor.fit(X_train_scaled,Y_train)

print(regressor.intercept_)
print(regressor.coef_)



[31.26170026]
[[  5.58919129 -38.23018134]]


In [50]:
vAge = 37.5 
vIstat = 4.65

sc = MinMaxScaler()
sc.fit(X_train)
scaled = sc.transform([[vAge, vIstat]])
print(f"Giá trị vAge và vIstat sau khi scale: {scaled}")
predicted = regressor.predict(scaled)
print(predicted[0])


Giá trị vAge và vIstat sau khi scale: [[0.35633368 0.08837772]]
[29.87462092]


In [5]:
X_train_scaled[0]

array([0.92481977, 0.49424939])

In [6]:
print(X_train.shape)

(404, 2)


In [7]:
Y_train[0]

array([15.2])

In [46]:
Y_test_pred = regressor.predict(X_test_scaled)
Y_train_pred = regressor.predict(X_train_scaled)
Y_test_pred[0]

array([30.30177452])

In [11]:
from sklearn import metrics
print('Score or R-Squared(test): ', regressor.score(X_test_scaled,Y_test))
print('Score or R-Squared(train): ', regressor.score(X_train_scaled,Y_train))
print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test,Y_test_pred))

print('Mean Squared Error:', metrics.mean_squared_error(Y_test,Y_test_pred))

print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(Y_test,Y_test_pred)))

print('Mean Absolute Percentage Error: ', metrics.mean_absolute_percentage_error(Y_test,Y_test_pred))

Score or R-Squared(test):  0.4069676937197577
Score or R-Squared(train):  0.5630979953818331
Mean Absolute Error: 4.5918745715026485
Mean Squared Error: 39.24693104001137
Root Mean Squared Error:  6.264737108611292
Mean Absolute Percentage Error:  0.2547803169337023
