In [1]:
import pandas as pd
df = pd.read_csv('./boston.csv')

In [2]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [3]:
# Tập dử liệu Input (đặc trưng) và Output (mục tiêu)
x = df[['AGE', 'LSTAT']].values # input
y = df[['MEDV']].values  # output

In [4]:
# chia tách ra training (huấn luyện) và testing (kiểm thử)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PolynomialFeatures
                                                                                          
# Tạo và huấn luyện MinMaxScaler
scaler = PolynomialFeatures(degree=2)
x_train_scaled = scaler.fit_transform(x_train)

# Tạo và huấn luyện mô hình Linear Regression trên dữ liệu đã được chuẩn hóa
regressor = LinearRegression()
regressor.fit(x_train_scaled, y_train)


LinearRegression()

In [6]:
# Dòng đầu tiên sau khi tiến hành chuẩn hóa dử liệu trên tập dử liệu đầu vào cho tập train
x_train_scaled

array([[1.000000e+00, 4.570000e+01, 1.345000e+01, 2.088490e+03,
        6.146650e+02, 1.809025e+02],
       [1.000000e+00, 1.000000e+02, 1.333000e+01, 1.000000e+04,
        1.333000e+03, 1.776889e+02],
       [1.000000e+00, 9.690000e+01, 2.034000e+01, 9.389610e+03,
        1.970946e+03, 4.137156e+02],
       ...,
       [1.000000e+00, 4.190000e+01, 1.334000e+01, 1.755610e+03,
        5.589460e+02, 1.779556e+02],
       [1.000000e+00, 8.840000e+01, 1.481000e+01, 7.814560e+03,
        1.309204e+03, 2.193361e+02],
       [1.000000e+00, 6.280000e+01, 1.045000e+01, 3.943840e+03,
        6.562600e+02, 1.092025e+02]])

In [7]:
print(x_train.shape)


(404, 2)


In [8]:
# Hệ số tự do
print(regressor.intercept_)

[37.41091648]


In [9]:
# Hệ số gốc
print(regressor.coef_)

[[ 0.00000000e+00  1.13055257e-01 -2.22833358e+00  2.61620589e-04
  -8.48261055e-03  5.89443702e-02]]


In [10]:
# Dòng đầu tiên trên dử liệu đầu ra trên tập dữ liệu train
y_train[0]

array([19.7])

In [11]:
import numpy as np
from sklearn import metrics
 
scaler.fit(x_train)

# Biến đổi dữ liệu kiểm thử
x_test_scaled = scaler.transform(x_test)

y_test_pred = regressor.predict(x_test_scaled)

print('Score or R-Squared: ', regressor.score(x_test_scaled, y_test))

# print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_test_pred))
# print('Mean Squared Error: ', metrics.mean_squared_error(y_test, y_test_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)))
print('Mean Absolute Percentage Error: ', metrics.mean_absolute_percentage_error(y_test, y_test_pred))

Score or R-Squared:  0.6397652446391968
Root Mean Squared Error:  6.137883866944747
Mean Absolute Percentage Error:  0.19108233634445346


In [12]:
# Kết quả dự báo đầu tiên cho giá trị medv
y_test_pred[0]

array([25.26299178])

In [13]:
# Dự báo giá trị medv khi biết giá trị vAge = 37.5 và vIstat = 4.65
vAge = 37.5 
vIstat = 4.65

scaled = sc.transform([[vAge, vIstat]])

print(f"Giá trị vAge và vIstat sau khi scale: {scaled}")

predicted = regressor.predict(scaled)

print(f"Giá trị dự báo medv: {predicted[0]}")

NameError: name 'sc' is not defined